os: linux
sudo: required
language: python
dist: xenial

python:
  - "3.7"
  - "3.8"
  - "3.9"


before_install:
  # gcc (gfortran is not there by default, we install all gcc suit just in case)
  - sudo apt-get install gcc
  - sudo apt-get install gfortran

  # keep record of kliff directory
  - export KLIFF_DIR=$PWD
  - export KIM_API_VERSION=2.1.2



install:
  # kim-api
  - cd $KLIFF_DIR && cd ..
  - wget http://s3.openkim.org/kim-api/kim-api-$KIM_API_VERSION.txz
  - tar Jxvf kim-api-$KIM_API_VERSION.txz
  - cd kim-api-$KIM_API_VERSION
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - sudo make install
  - sudo ldconfig
  # install SW driver and model
  - kim-api-collections-management install user SW__MD_335816936951_004
  - kim-api-collections-management install user SW_StillingerWeber_1985_Si__MO_405512056662_005

  # kimpy
  - pip install kimpy


script:
  - cd $KLIFF_DIR
  - pip install -e .
  - cd tests
  - pytest
